### ISSUE TITLE
integration-http inbound with no Content-Type header

### ISSUE THREAD

**Issue by an-sush** [spring-projects/spring-integration-samples#160]
Hello,
I imported spring-int-basic-http example and ran the request using Fiddler. Here is my URL and request header:
URL: http://localhost:8080/http-4.1.0.BUILD-SNAPSHOT/receiveGateway
Method: Post
HTTP Headers: User-Agent: Fiddler
Host: localhost:8080
Content-Length: 93

The response is blank. If I add a request header:
Content-Type: text/plain
I get response from server. Please help me with this. I have a client application which is hitting the URL without passing Content-Type and hence I am unable to read the request body.

**Comment by garyrussell** [comment]
See [INT-3934](https://jira.spring.io/browse/INT-3934) for a fix on master (4.3) and a work-around for earlier versions.
