### ISSUE TITLE
Two Different inbound adapters for single SFTP Server

### ISSUE THREAD

**Issue by vayalaivadivel** [spring-projects/spring-integration-samples#167]
Hi Team, 
         Is it possible to have two different inbound adapters for single SFTP Server?
         If yes, Please let me know the configuration of adapters using spring annotation (JDK1.9)
         In addition to that more than one type of file filters.
Thanks and Regards,
VADIVEL P M.

**Comment by garyrussell** [comment]
Github Issues are for raising problems or new feature requests, not for asking questions - please use StackOverflow (spring-integration tag) for questions.

Yes, you can use multiple adapters to talk to the same server, just configure a single `DefaultSftpSessionFactory` `@Bean` and inject it into both adapters.

We recently added information to the [reference documentation](http://docs.spring.io/spring-integration/docs/4.3.0.BUILD-SNAPSHOT/reference/html/overview.html#programming-tips) about how to build various adapters using java configuration. In this case you will need `SftpInboundFileSynchronizingMessageSource` and `SftpInboundFileSynchronizer` `@Bean`s.

**Comment by vayalaivadivel** [comment]
Ok thanks

**Comment by artembilan** [comment]
Closed with the power of the comments above.

Note: there is [Java DSL](https://github.com/spring-projects/spring-integration-java-dsl) library to simplify your life when you are with Java 8.
