### ISSUE TITLE
message is not deleted from the queue post read

### ISSUE THREAD

**Issue by ashwgupt** [spring-projects/spring-integration-samples#170]
This is not really an issue with RabbitMq but more of a help required in order to implement a SimpleMessageListenerContainer in a manner that it removes the message, un-transactionally, as soon read by the message receiver.

But in my case, irrespective of successful or unsuccessful transactions, the message remains in the queue, causing its repeated processing.

Below is the code snippet of my container bean configuration, it will be of great help if someone can point out the mistake in here:-

```
@Bean
SimpleMessageListenerContainer container(ConnectionFactory connectionFactory, MessageListenerAdapter listenerAdapter) {
        SimpleMessageListenerContainer container = new SimpleMessageListenerContainer();
        container.setAcknowledgeMode(NONE);
        container.setConnectionFactory(connectionFactory);
        container.setQueueNames(queueName);
        container.setMessageListener(listenerAdapter);
        return container;
    }
```

**Comment by artembilan** [comment]
Such kind of questions about the help must be asked on [StackOverflow](http://stackoverflow.com).

The GitHub issues are exactly for issues or changes requests in the Framework.

Right now I don't have any immediate answer to you, so, please, move the question there with the `spring-amqp` tag.

Some test-case to play locally would be great, too.
