### ISSUE TITLE
why i can not download the jars in pom.xml

### ISSUE THREAD

**Issue by Enan01** [spring-projects/spring-integration-samples#187]
+ spring-integration-kafka
+ spring-integration-core
+ spring-kafka
+ spring-kafka-test
these all can not download, can anybody tell me why ?

**Comment by garyrussell** [comment]
Where are you trying to download them from? They are all in maven central, Bintray, and the spring.io repository.

**Comment by mohamad7788** [comment]
Those are part of Spring dependencies , you need just to specify what do you need and it will be downloaded from Maven Spring.io repository , once you run maven build step

**Comment by artembilan** [comment]
Closed as *Invalind* without reporter's feedback for a long period.
