### ISSUE TITLE
Declaring control bus in java config

### ISSUE THREAD

**Issue by psoares** [spring-projects/spring-integration-samples#189]
Hi,
How can I configure a control bus in a java configuration file ? All the examples and docs I see show how to declare it in xml, but I don't know which class gets instantiated.

Thank you.

**Comment by artembilan** [comment]
```
@Bean
@ServiceActivator(inputChannel = "controlBusChannel")
public ExpressionControlBusFactoryBean controlBus() {
	return new ExpressionControlBusFactoryBean();
}
```
or using Java DSL:
```
@Bean
public IntegrationFlow controlBusFlow() {
	return IntegrationFlows.from("controlBus").controlBus().get();
}
```
We will add a sample to the Reference Manual later.
