### ISSUE TITLE
Kafka basic example doesn't work properly

### ISSUE THREAD

**Issue by dcortesf** [spring-projects/spring-integration-samples#205]
Hi guys,

I'm trying to run the kafka basic example and I'm getting this error:

**Sending 10 messages...ECUTING
Sending a null message...
GenericMessage [payload=foo0, headers={kafka_offset=11, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368943}]
GenericMessage [payload=foo1, headers={kafka_offset=12, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo2, headers={kafka_offset=13, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo3, headers={kafka_offset=14, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo4, headers={kafka_offset=15, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo5, headers={kafka_offset=16, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo6, headers={kafka_offset=17, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo7, headers={kafka_offset=18, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo8, headers={kafka_offset=19, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=foo9, headers={kafka_offset=20, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368955}]
GenericMessage [payload=org.springframework.kafka.support.KafkaNull@150d80c4, headers={kafka_offset=21, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62d0ac62, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=si.key, kafka_receivedPartitionId=0, kafka_receivedTopic=si.topic, kafka_receivedTimestamp=1496067368962}]
Adding an adapter for a second topic and sending 10 messages...
Exception in thread "main" java.lang.AbstractMethodError: Method org/springframework/integration/kafka/dsl/KafkaMessageDrivenChannelAdapterSpec$KafkaMessageDrivenChannelAdapterListenerContainerSpec.getComponentsToRegister()Ljava/util/Map; is abstract
        at org.springframework.integration.kafka.dsl.KafkaMessageDrivenChannelAdapterSpec$KafkaMessageDrivenChannelAdapterListenerContainerSpec.getComponentsToRegister(KafkaMessageDrivenChannelAdapterSpec.java)
        at org.springframework.integration.dsl.IntegrationFlows.registerComponents(IntegrationFlows.java:333)
        at org.springframework.integration.dsl.IntegrationFlows.from(IntegrationFlows.java:221)
        at org.springframework.integration.samples.kafka.Application.addAnotherListenerForTopics(Application.java:166)
        at org.springframework.integration.samples.kafka.Application.runDemo(Application.java:95)
        at org.springframework.integration.samples.kafka.Application.main(Application.java:74)
<=========----> 75% EXECUTING**

I've created the topic that you mentioned en README.md. If I try to publish and consum using kafka bash scripts, it works fine. 

My setup;

Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.4.0-78-generic amd64

Thanks in advanced.

**Comment by artembilan** [comment]
It has not been merged yet : https://github.com/spring-projects/spring-integration-kafka/pull/167

Thank you for heads up! I hope will address that tomorrow. Today is holiday here for us.

/CC @garyrussell

**Comment by garyrussell** [comment]
I've merged that PR (we really shouldn't have the samples on snapshot dependencies to avoid problems like this).

However, after changing the sample to use the spring-integration-kafka 3.0.0.BUILD-SNAPSHOT, the dynamic part of the sample still doesn't work; it doesn't crash but it never receives the records.

For some reason, the message-driven adapter is not in the registration's `integrationComponents` - only the consumer and channel are there; so the container is never started.

![image](https://cloud.githubusercontent.com/assets/483832/26555582/af94c600-4463-11e7-9d25-7dc1521a63b7.png)

**Comment by garyrussell** [comment]
@dcortesf the 4.3.x branch should be stable.

**Comment by dcortesf** [comment]
@artembilan @garyrussell Now it works fine =)

Thanks a lot.

**Comment by artembilan** [comment]
All related issues has been fixed.
Closing...

Thank you, @dcortesf , for being in time with samples tackling that let us to fix our new feature as fast as possible and therefore make Framework much robust 😄
