### ISSUE TITLE
Are spring web sockets a single http connection per subscription?

### ISSUE THREAD

**Issue by nodevm** [spring-projects/spring-integration-samples#216]
I have a web page that makes use of spring web sockets. I have one subscription and that does work as expected. However, i need the web page to subscribe to more than 100 objects. let me explain what the 100 objects are.

I have a registered user who must login and receive realtime data from 100+ Gps devices and i need to display the location of the devices to the logged in user.

With over 5000 users of the app, i can theorize that at any one time, my app will need to handle 500,000 concurrent web socket connections.

Does spring create a new http connection for every subscription?.

Can i make a web page subscribe to those many objects without running into problems?.

Can spring handle those many concurrent web socket connections?

**Comment by artembilan** [comment]
Too much context and not related to this project.

Please, consider to raise similar concern on some Community forum, e.g. [StackOverflow](https://stackoverflow.com).
