### ISSUE TITLE
Aggregate Processor

### ISSUE THREAD

**Issue by RanjithMohandasss** [spring-projects/spring-integration-samples#222]
Hi @artembilan ,

There is a requirement for us to create a sequential pipeline where we will be getting one MessagePayload and the same payload has to go through sequence of aggregators(one after the other) and perform certain operations (e.g. updating repositories etc) and finally it has to finish.. Could you please let me know how to achieve this..i am planning to do it like below

IntegrationFlows.from("input").aggregate(
                processor1-> processor1.outputProcessor(g -> new Processor1().receiver(
                        g.getMessages().
                                stream().map(message1 -> message1.getPayload()).
                                collect(Collectors.toList()))).correlationStrategy(m->m.getHeaders().containsKey("correlation"))
        ).aggregate(processor2-> processor2.outputProcessor(g -> new Processor2().receiver(
                g.getMessages().
                        stream().map(message1 -> message1.getPayload()).
                        collect(Collectors.toList()))).correlationStrategy(m->m.getHeaders().containsKey("correlation"))).

             channel(output()).get();

Please let me know whether the understanding is correct

**Comment by artembilan** [comment]
Unfortunately this is not the place to ask questions. Consider to move to the StackOverflow. Right, you can use `spring-integration` tag and we or someone else from the community will back to you with the answer or will ask more information.

Right now it’s not clear what you are asking, so I have nothing to say you immediately.
