### ISSUE TITLE
Can't compile/run in Eclipse

### ISSUE THREAD

**Issue by GTAtWork** [spring-projects/spring-integration-samples#228]
Hey Guys, thanks for making this samples repository available to those of us learning Spring Integration.

Getting few issue as I import project into Eclipse. 
Hope I can get a head start on one of my projects with this sample and am missing something simple and easy to fix in my configuration. (I'm able to build/run other projects from this repo and think my env. more-or-less stable at this juncture)

> Lambda expressions are allowed only at source level 1.8 or above	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 72	Java Problem
> Lambda expressions are allowed only at source level 1.8 or above	SftpTestUtils.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 45	Java Problem
> Lambda expressions are allowed only at source level 1.8 or above	SftpTestUtils.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 63	Java Problem
> Lambda expressions are allowed only at source level 1.8 or above	SftpTestUtils.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 80	Java Problem
> The method afterPropertiesSet() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 70	Java Problem
> The method getPhase() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 118	Java Problem
> The method isAutoStartup() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 113	Java Problem
> The method isRunning() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 156	Java Problem
> The method setSubsystemFactories(List<NamedFactory<Command>>) in the type SshServer is not applicable for the arguments (List<SftpSubsystemFactory>)	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 75	Java Problem
> The method start() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 123	Java Problem
> The method stop() of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 141	Java Problem
> The method stop(Runnable) of type EmbeddedSftpServer must override a superclass method	EmbeddedSftpServer.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 135	Java Problem
> The target type of this expression must be a functional interface	SftpTestUtils.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 45	Java Problem
> The target type of this expression must be a functional interface	SftpTestUtils.java	/sftp/src/test/java/org/springframework/integration/samples/sftp	line 63	Java Problem
> 
>

**Comment by garyrussell** [comment]
Which sample, specifically? Are you importing using gradle or maven?

**Comment by GTAtWork** [comment]
Gary, thanks for quick response.

My bad I didn't bother to check JRE version -- changing project level Build Path to use JavaSE-1.8 has fixed compilation issue for `/basic/sftp` project. 
Now trying to run and explore functionality.



`/basic/ftp` just won't build 

> .\spring-integration-samples-master>gradlew :ftp:run
> Starting a Gradle Daemon (subsequent builds will be faster)
> FAILURE: Build failed with an exception.
> * What went wrong:
> Task 'run' not found in project ':ftp'.
> BUILD FAILED in 7s

**Comment by artembilan** [comment]
That's correct: the `gradlew :ftp:run` is not going to work because there is no `application` plugin in that sub-project:
```
project('ftp') {
	description = 'FTP Basic Sample'

	dependencies {
		compile "org.springframework.integration:spring-integration-ftp"
		compile "commons-io:commons-io:$commonsIoVersion"
		compile "org.apache.ftpserver:ftpserver-core:$ftpServerVersion"
		compile "org.slf4j:slf4j-api:$slf4jVersion"

		runtime "org.slf4j:slf4j-log4j12:$slf4jVersion"

		testCompile "org.apache.logging.log4j:log4j-core:$log4jVersion"
		testCompile "org.springframework.integration:spring-integration-test"
	}

	test {
		include '**/TestSuite*'
	}
}
```

To be honest there is just no classes in `main` of that project at all - only tests.

I think we need to fix `README.md` for that project to mention ` :ftp:test` instead.
