### ISSUE TITLE
Add a sample that sends messages to all connected tcp clients

### ISSUE THREAD

**Issue by dty717** [spring-projects/spring-integration-samples#234]
I get the message from spring mvc controller, and I want to send message to all the connected clients.
I use xml and not springboot.
and another question can i get the socket without any channel,any activator...

**Comment by garyrussell** [comment]
GitHub issues are not for asking questions; they are for reporting bugs and asking for new features.

Call `getOpenConnectionIds()` on the connection factory and, for each, set the `IpHeaders.CONNECTION_ID` property and send the message to the outbound channel adapter.

**Comment by dty717** [comment]
but there is no code demo as you said,hard to find.
