### ISSUE TITLE
DefaultPahoMessageConverter

### ISSUE THREAD

**Issue by theanswer0815** [spring-projects/spring-integration-samples#236]
The class Could not compile success. Assert.isTrue function(279 line) uses the lambda shows error in my ideal environment. how to solve problem?  which jar has got the class file  BytesMessageMapper? thx.

**Comment by garyrussell** [comment]
You need to provide much more information for questions like this (jar versions, pom etc).

My best guess is you are trying to use Spring Integration 5.x with Spring Framework 4.3.x (or earlier). The lambda versions of `Assert.*` were added in Spring Framework 5.

It is generally best to use something like maven or gradle to manage versions so the correct transitive versions are pulled in.

**Comment by theanswer0815** [comment]
Awesome!!! Idol. your guess is correct. thx very very much for help.
