### ISSUE TITLE
I have java TCP server running separately

### ISSUE THREAD

**Issue by Ajayr84** [spring-projects/spring-integration-samples#239]
I have spring TCP client that needs to send request via outbound gateway.
TCP server socket pgm able to read the request and send reply to client.
How to receive the reply.

Time-out exception is coming.

Configured only Client side XML ..
Used simple gateway to send message

**Comment by artembilan** [comment]
Sounds like a StackOverflow question: fully not clear how is it related to this project...

Please, raise your issue over there with more details.

Thanks for understanding.

**Comment by Ajayr84** [comment]
Thanks will do..
