### ISSUE TITLE
Spring Integration SFTP

### ISSUE THREAD

**Issue by sarsatis** [spring-projects/spring-integration-samples#269]
I'm integrating spring integration SFTP to a legacy application while reading it from the xml it is giving the following error could you please help me with it

org.xml.sax.SAXParseException;  Failed to read schema document

**Comment by artembilan** [comment]
Sorry, not enough info.

Please, consider to raise questions on StackOverflow.

The GitHub issues are for bug reports and feature requests.

Thanks for understanding.
