### ISSUE TITLE
jdk 7 in the pom.xml while using lambda expressions

### ISSUE THREAD

**Issue by mxhdx** [spring-projects/spring-integration-samples#275]
In the pom.xml you specify source and target = 7 for cmaven-compliler-plugin.
However in the JmsMockTests you are using Lambda Expressions that are not part of jdk 7.

**Comment by artembilan** [comment]
This the POM which is generated for the mentioned sample: https://github.com/spring-projects/spring-integration-samples/blob/master/advanced/advanced-testing-examples/pom.xml

As you see we don't specify any Java version in it, nor the mentioned `cmaven-compliler-plugin`.

So, I'm confused what you are talking about. 

If you see something we can fix on our side, please, feel free to raise a Pull Request and we'll take a look shortly.

Thanks

**Comment by mxhdx** [comment]
My error. Intellij added that for me, i was not versioned I used the zip.
