### ISSUE TITLE
amqp cafe application sample broken due to ClassCastException

### ISSUE THREAD

**Issue by benediktbrandt** [spring-projects/spring-integration-samples#277]
When I run the amqp cafe application sample I get a 

`ClassCastException: org.springframework.integration.samples.cafe.OrderItem cannot be cast to org.springframework.integration.samples.cafe.Drink`

in the `Waiter.prepareDelivery` method. I tried both the master and the 5.2.x branch. 

I looked through the code and the configuration xml files, but the reason is escaping me. Everything seems to be correctly wired up. 

`<int:json-to-object-transformer id="json-to-drink" input-channel="preparedJsonDrinks" output-channel="preparedDrinks" type="org.springframework.integration.samples.cafe.Drink"/>`

should deserialize incoming messages to `Drink` objects, yet they get deserialized to `OrderItem`.

Attached is a full console output & stack trace.
[trace.txt](https://github.com/spring-projects/spring-integration-samples/files/4113673/trace.txt)

**Comment by artembilan** [comment]
I found the reason.
When we send a message over AMQP we populate `JsonHeaders` in the request. In this case we send an `OrderItem`.
One of the headers is a `JsonHeaders.RESOLVABLE_TYPE` .
Then when we receive a reply it is already a `Drink`, with appropriate `__Type__` and `JsonHeaders.TYPE_ID` headers, but there is no a `JsonHeaders.RESOLVABLE_TYPE` in the reply, so we copy it from the request message.
Downstream when we come to the `JsonToObjectTransformer` it checks first for the `JsonHeaders.RESOLVABLE_TYPE` ignoring all others.
That's where we have a wrong deserialization.

I treat this as a bug and we definitely have to address in Spring Integration core.
There is nothing wrong with the sample.

Thank you for reporting this!
And we'd appreciate if you could raise an issue in the https://github.com/spring-projects/spring-integration/issues so we would have a track.

As a workaround you can place a `<int:header-filter header-names="json__resolvableType" />` before that `<int:json-to-object-transformer id="json-to-drink" input-channel="preparedJsonDrinks" output-channel="preparedDrinks" type="org.springframework.integration.samples.cafe.Drink"/>` to remove that misleading header and fully rely on the `JsonHeaders.TYPE_ID` for deserialization.
