### ISSUE TITLE
"hi sent to MQTT, received from MQTT", Message not received!

### ISSUE THREAD

**Issue by Mouli-Shankar** [spring-projects/spring-integration-samples#278]
[L114](https://github.com/spring-projects/spring-integration-samples/blob/4ff6288db51ca93503e681e029b742be222056fc/basic/mqtt/src/main/java/org/springframework/integration/samples/mqtt/Application.java#L114): "p + ", received from MQTT"" value **p** (sent message) is not recieved.
```java
return IntegrationFlows.from(mqttInbound())
	.transform(p -> p + ", received from MQTT")
	.handle(logger())
	.get();
```
## Output
```
12:53:09.415 [MQTT Call: siSampleConsumer] INFO  siSample - hi sent to MQTT, received from MQTT
```
Should be
```
12:53:09.415 [MQTT Call: siSampleConsumer] INFO  siSample - hi sent to MQTT, hi received from MQTT
```

**Comment by garyrussell** [comment]
??

    .transform(p -> p + ", received from MQTT")

if `p` is "hi sent to MQTT` then what you are getting is completely what you should expect.

You are simply concatenating `", received from MQTT"` to the inbound message.

**Comment by garyrussell** [comment]
??

    .transform(p -> p + ", received from MQTT")

if `p` is "hi sent to MQTT` then what you are getting is completely what you should expect.

The sample is simply concatenating `", received from MQTT"` to the inbound message. There is no logic to parse out the "hi" part.

**Comment by Mouli-Shankar** [comment]
Understood thanks for your explanation.
