### ISSUE TITLE
Unresolved publisher-confirms in basic/amqp sample

### ISSUE THREAD

**Issue by nikhilvasaikar** [spring-projects/spring-integration-samples#285]
In the [Config File](https://github.com/spring-projects/spring-integration-samples/blob/master/basic/amqp/src/main/resources/META-INF/spring/integration/spring-integration-confirms-context.xml)

At line 63 
`	<rabbit:connection-factory id="connectionFactory" host="localhost" publisher-confirms="true" publisher-returns="true" />`

Schema Validation error.

`Caused by: org.xml.sax.SAXParseException; lineNumber: 63; columnNumber: 122; cvc-complex-type.3.2.2: Attribute 'publisher-confirms' is not allowed to appear in element 'rabbit:connection-factory'.`

**Comment by garyrussell** [comment]
Thanks.
