### ISSUE TITLE
Two permanents connections with RoundRobin and Failover 

### ISSUE THREAD

**Issue by higonetr** [spring-projects/spring-integration-samples#286]
Hey,

It's possible (using the existing components of Spring-Integration) to have two permanents connections to two differents TCP Servers, that allow us to make a round-robin between the connections, and on the case of fails, try with the other connection? 

We are using the FailoverClientConnectionFactory, with two TcpNioClientConnectionFactory (each one to connect to a different server).
But that means that our application it's working at 50%. Because it's using a shared connection, and we could make a round-robin to use the two TCP servers. 

I'm struggling with this scenario
We are considered to make our own CustomRoundRobinFailoverConnectionFactory or use the IntegrationFlow library, but maybe it's a better way to do it.
Thanks for advance! (I don't know where it's the correct channel to put this message)

**Comment by artembilan** [comment]
Sounds more like StackOverflow question...
We will try our best to help you there.

Thanks

**Comment by artembilan** [comment]
The SO question for the whole picture: https://stackoverflow.com/questions/63195590/spring-integration-two-permanents-connections-with-roundrobin-and-failover

**Comment by higonetr** [comment]
Sorry for posting the question here
Thanks!

**Comment by garyrussell** [comment]
https://stackoverflow.com/questions/63195590/spring-integration-two-permanents-connections-with-roundrobin-and-failover/63196351#63196351
