### ISSUE TITLE
JSON or Pipe(|) based DSL for dynamic flow generation in Spring Integration

### ISSUE THREAD

**Issue by ankitravan** [spring-projects/spring-integration-samples#287]
We are creating a few SI flows using Java DSL. All flows are clubbed in a single Spring boot app, which makes us redeploy the app every time whenever we add new flow. I was curious if somehow we abstract flow creation in a JSON format or a pipe-delimited flow instruction. So that we can create flow dynamically and register it. I already tried to search regarding this and found nothing. Please guide me in the right direction to achieve it if it is possible..?

Please refer to the below link for StackOverflow.

https://stackoverflow.com/questions/63266139/json-or-pipe-based-dsl-for-dynamic-flow-generation-in-spring-integration

**Comment by artembilan** [comment]
Please, don't duplicate your questions in different place.
And this sounds more like a feature request, rather then a samples project issue.
I'll reach you on StackOverflow.

Thanks for understanding.
