### ISSUE TITLE
How do I create multiple MQTTClients and generate messages using Spring-Integration-MQTT? 

### ISSUE THREAD

**Issue by qq2429979710** [spring-projects/spring-integration-samples#330]
I looked at the MQTT sample code and found that the initialization creates mqttOutbound and specifies clientId so that only an MQTT client can be created from clientId  
 
Like this: 
```
 Map<String,MqttClient> map = new ConcurrentHashMap<>();
            MqttClient client = new MqttClient(serverUrl, clientId, new MemoryPersistence());
            map.put(clientId,client);
```
Clients can be maintained according to ClientId 

How to use Spring-Integration-MQTT to achieve this effect, according to the client ID convenient operation of the client  

The client can be created through the HTTP interface  
 
Convenient to provide sample code, thank you

**Comment by garyrussell** [comment]
You would need to create a new adapter for each.

You can use dynamic flow registration for that.

https://docs.spring.io/spring-integration/docs/current/reference/html/dsl.html#java-dsl-runtime-flows
