### ISSUE TITLE
Server-side logging seems to be broken

### ISSUE THREAD

**Issue by swiss-chris** [spring-projects/spring-integration-samples#340]
When running this Application, I expected to see a log message being printed in the console every second, according to the format defined inside `loggingChannelAdapter()`. Something like: 

`The time 23 December 2022, 15:25:34 has been sent to the WebSocketSession WebSocketClient-AsyncIO-10`

Am I missing something or is it broken ?

This would be very helpful, because the first time I ran the server application, I though something was broken, because all the console logs ist the Spring Boot banner and then the line:

`Hit 'Enter' to terminate`

https://github.com/spring-projects/spring-integration-samples/blob/5dd165b349d92c3e405dc0cfba3e811be27dcad7/basic/web-sockets/src/main/java/org/springframework/integration/samples/websocket/standard/server/Application.java#L132

**Comment by swiss-chris** [comment]
PS: I tried a few things to get it to work, but was unsuccessful. I'm used to logging with the DSL, but I'm not familiar with logging in the basic (non-DSL) SI.

**Comment by artembilan** [comment]
Fixed in the latest `main`.

The `log()` in Java DSL is fully based on the `LoggingHandler`, so I'm not sure what problem have you faced to trying few things: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#logging-channel-adapter
