### ISSUE TITLE
IMAP with OAuth 2 authentication 

### ISSUE THREAD

**Issue by dmitryallen** [spring-projects/spring-integration-samples#341]
Hello, 
is there possibility to get sample IMAP integration with OAuth 2 authentication ?

**Comment by garyrussell** [comment]
See https://javaee.github.io/javamail/OAuth2

It looks like this needs a change in `AbstractMailReceiver` in the main project, to pass the token into the `connect()` method.

**Comment by artembilan** [comment]
Why is the question for Spring Integration, but not directly to Java Mail API, where that OAuth 2 authentication resides?
Spring Integration does nothing special in this area unless exposes an `AbstractMailReceiver.javaMailAuthenticator` option where we indeed should implement any possible dynamic authentication mechanism.
That `Authenticator.getPasswordAuthentication()` implementation should get the current use calling `getDefaultUserName()`.
Then you perform your API to obtain an OAuth token and return new `PasswordAuthentication` with both of them.

**Comment by dmitryallen** [comment]
Thanks Garry and Artem,
I'm just looking for sample code with Mail Integration using OAuth 2 and I could not find any working code.
Looks like in near future OAuth 2 will be the main method to authenticate mailboxes in automation tasks. 
Microsoft is deprecating old password authentication in Azure. 
[https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fexchange%2Fclients-and-mobile-in-exchange-online%2Fdeprecation-of-basic-authentication-exchange-online&data=05%7C01%7Cdallen%40axionhealthcare.com%7Ceb8cd2998468491cb1dc08daf99d468d%7C11e9061f66684959a5416b7f010efed5%7C1%7C0%7C638096751183153080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FxoiUXwB8qjYmM6TQxjMCiUhDO4%2Bn8aYUqLwTgHod%2BI%3D&reserved=0)
[https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-time-s-up/ba-p/3695312](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fexchange-team-blog%2Fbasic-authentication-deprecation-in-exchange-online-time-s-up%2Fba-p%2F3695312&data=05%7C01%7Cdallen%40axionhealthcare.com%7Ceb8cd2998468491cb1dc08daf99d468d%7C11e9061f66684959a5416b7f010efed5%7C1%7C0%7C638096751183153080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B%2FFRMur1YVYZrZMKOn0b5Oa11cKKbMw%2B%2FFhfFNjk97c%3D&reserved=0)

Artem, this repository is [spring-integration-samples], so authentication related question can be relevant here.
I thought that you already have sample code for mail integration with OAuth 2 or working on it.

Thanks 
Dmitry

**Comment by artembilan** [comment]
Well, this repository is for samples based on Spring Integration solutions: https://spring.io/projects/spring-integration.
Mostly about channel adapters to this or that system.
We demonstrate here components from this framework and how they work together.
Spring Integration does not owe OAuth for email API. That is native Java Mail feature.

We will be glad to add something OAuth-based into existing mail samples, but for that purpose we need to learn more and will be glad to accept any contributions on the matter.
Although if I would search this feature I'd go first to Java Mail project.

To be more specific: what is your take on that `jakarta.mail.Authenticator` API?

**Comment by dmitryallen** [comment]
Thanks Artem, 
it's clear about Authenticator, I can initialize JavaMailSenderImpl with OAuth and implement renew of session.
There is not possibility to set mail-sender in inbound-channel-adapter, this attribute is available only in outbound-channel-adapter


```
JavaMailSenderImpl mailSender = new JavaMailSenderImpl();

            mailSender.setHost("imap-mail.outlook.com");
            mailSender.setPort(993);

            Properties props = mailSender.getJavaMailProperties();
            props.put("mail.imap.ssl.enable", "true");
            props.put("mail.imap.auth.mechanisms", "XOAUTH2");
            props.put("mail.debug", "true");
            props.put("mail.debug.auth", "true");

            String authToken = beanOAuth.getAuthToken();

            Session session = Session.getInstance(props, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {

                    String token = beanOAuth.getAuthToken();

                    return new PasswordAuthentication(_smtpUser, token);
                }
            });

            session.setDebug(true);

            Store store = session.getStore("imap");
            store.connect("imap-mail.outlook.com", _smtpUser, authToken);

            mailSender.setSession(session);


            return mailSender;
```

**Comment by dmitryallen** [comment]
It's my current configuration 


![2023-01-18 16_41_42-Window](https://user-images.githubusercontent.com/40036653/213311531-bc2d2c08-a781-4526-be9d-423503c5b66d.png)

**Comment by artembilan** [comment]
Right. That's what I mean. The `<mail:imap-idle-channel-adapter>`, for example, has respective attribute:
```
		<xsd:attribute name="authenticator" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>
					Specify the jakarta.mail.Authenticator.
					NOTE: if this is provided, then 'session' should not be.
				</xsd:documentation>
				<xsd:appinfo>
					<tool:annotation kind="ref">
						<tool:expected-type type="jakarta.mail.Authenticator"/>
					</tool:annotation>
				</xsd:appinfo>
			</xsd:annotation>
		</xsd:attribute>
```

Same attribute is present on regular `<mail:inbound-channel-adapter>` polling channel adapter.
I agree that we don't document this attribute anyhow here: https://docs.spring.io/spring-integration/reference/html/mail.html#mail-namespace.
But nothing stops us to improve that end-user experience.

Let's us know if that option works for you as separate bean and we will document it respectively!

Not sure how dynamic OAuth works with Gmail to make respective changes in the current sample in this project...

**Comment by dmitryallen** [comment]
Thanks Artem, 
it's working well, so we can close this ticket.
